apiVersion: v1
kind: Service
metadata:
  name: {{ include "emote-chat-server.name" . }}
  labels:
    {{- include "emote-chat-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "emote-chat-server.name" . }}
  ports:
    - port: {{ .Values.app.container.port }}
      targetPort: {{ .Values.app.container.port }}
